### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by SomeCatIDK** [RocketMod/Rocket.Eco#1]
ugh this will be long

- [x] Finish the deflation methods of the AssemblyExtractor
- [x] Finish the extraction methods of the AssemblyExtractor
- [x] Create the patcher and patching methods.
- [ ] Finish the RocketMod rework to strip the dependency of Unity.
- [ ] Implement the Rocket base.
